### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by bkrantz**
Useful tool to help minimize code elsewhere.

### CODE REVIEW

**Comment by drpoggi** [comment]
Sorry about the delay. What would be some example use cases for this? My main concern is that we could end up ignoring exceptions which are raised by cases that weren't considered when applying the decorator.

**Comment by bkrantz** [comment]
So lines 363-366 in event.py

`try:`
`error = etree.tostring(error, pretty_print=True)`
`except Exception:`
`pass`

Would look like this instead

`with ignore(Exception):`
`error = etree.tostring(error, pretty_print=True)`

So there would be no functional changes. I'm thinking to just help make code more readable/pretty/simple.

**Comment by drpoggi** [comment]
Ideally I think we'd want to move away from doing that kind of "pokemon" exception handling (although we have that in at least a handful of places currently), so I'm hesitant to add something which could encourage it. Typically if we're ignoring errors I think we'd at least want to be able to log them, and if we're ignoring errors like this I'm not sure it's a bad thing that we need to make it ugly.

I see the utility, but I'm not sure if the benefits outweigh the potential negatives. I'm unsure about that opinion though, and I may be worrying about a non-problem. @donvier thoughts?

**Comment by bkrantz** [comment]
I agree we should definitely avoid catch-alls.  That was just an example (which already happened to be a catch-all) of how this could be used in our current code base.  As it functionally necessary I'm fine without it but it is a feature of contextlib in python 3 (contextlib.suppress) and I thought it'd be nice to be able to use in python 2.

https://docs.python.org/3/library/contextlib.html

**Pull request merged**
