### PR TITLE
Pytest, Refactoring, Unit Testing

### PR DESCRIPTION
**Pull request by bkrantz**
Integrated Pytest, Refactored Event Generators which originated from a need for a single thread (for lack of a better word) generator.  Where a generator only has a single active event.  Also added some unit tests to make sure I wasn't breaking anything.  All tests from commit 2 passed prior to making more changes to the tests for better coverage.

### CODE REVIEW

**Comment by drpoggi** [comment]
Looks good, couple questions:

1. Does using pytest change how we need to run the tests, or does that somehow happen automatically when Travis did `python setup.py test'?
2. Did the switch to pytest cause a conflict with the name `TestActorWrapper` starting `Test`? Only ask because we'll need to change where that's used in EIT as well.

**Comment by bkrantz** [comment]
So 'pytest' is an alternative to using 'python setup.py test'.  Both will run the tests but pytest works in conjunction with pytest-cov and pytest-socket.

I had originally changed TestActorWrapper to ActorWrapperTest because pytest was trying to execute it as a test class (prepended with 'Test').  Though after I started playing with the pytest init I was able to define where it would look for test classes.  I ended up moving it out of the main compysition directory as it didn't seem like the logical place for it as it appeared to be only used for tests.  I am not terribly attached in those changes so if it's being used in another project it may be best just to change it back.

**Comment by drpoggi** [comment]
1. Cool, then we probably also want to change `.travis.yml` to use that new method
2. Yeah I'd say change it back so we don't have to worry about also changing the other project

**Comment by bkrantz** [comment]
Should be good now

**Pull request merged**
