### PR TITLE
added __slots__ to events; improved pickling functionalities

### PR DESCRIPTION
**Pull request by bkrantz**
Added __slots__ to event classes.  My primary concerns with this were reducing the memory footprint while maintaining dynamicness.  Adding slots for known event attributes alongside __dict__ still decreases the size of the __dict__.  The size of the __dict__ is determined by the use of none slotted attributes and is only created when referenced.  The adding of slots makes pickling slightly slower but helps reduce memory footprint and is more than offset by the included pickling changes.  See memory tests in test_events.py.

Improved pickling functionalities.  There are several pickling protocols that increase in efficiency as the protocol level increases.  We were using the lowest in mdpactors.py.  It also turns out pickling and unpickling an Event is faster than deepcopy and performs the same function.  By utilizing that knowledge I was able to improve the speed at which we send events between actors.  See speed tests in test_actors.py and test_events.py.

### CODE REVIEW

**Comment by drpoggi** [comment]
@bkrantz can you share some of the memory improvement metrics? I know the memory tests should be outputting those, but I'm not seeing them show up in the output logs when I run them; I'm assuming there's some way to fix that? This adds some complexity and will require some changes to how some internal stuff uses events, so I'd like to know how significant the memory savings are.

**Comment by bkrantz** [comment]
@drpoggi Not knowing exactly how you are trying to run them, the speed/memory tests are removed from the build tests by prefixing the test with an underscore.  In order to run them via pytest you need to remove that.  Once running the tests, adding the '-s' command line argument to your pytest allows you to view the stdout of given tests.  Also, I added another test for a direct comparison of old(current) vs new(slotted) events.

Let me know if you still have issues because I would prefer that you see the results yourself rather than me copy-pasting mine.

As an aside, I added back the old Event classes under testutils for the old vs new comparison but (and I'm assuming you'd agree) if we move forward with this I would like to remove that.

**Comment by drpoggi** [comment]
On a closer look, it sounds like most of the memory savings come from reduced memory usage in LogEvents? Would it be possible to just change the LogEvents to start using slots, use that as base to see how it works for a while, then evaluate doing it for standard events as well? I think we pretty much know how LogEvents are used so that change would worry me the least; I've found a couple places where we'll need to change things if we switch to this as-is, and I'm sure there are many more lurking in areas I haven't thought to check.

**Comment by bkrantz** [comment]
I think that is doable let me rework some things.  

For understandings sake as I am thinking of adding a DeprecationWarning, are those places that will require changes, references to an event's __dict__ outside of the Event class definitions?

**Comment by drpoggi** [comment]
Yeah, so far that's the only thing I've seen that needs fixing. Just changing that on its own should be easy, but I'm worried there are other more subtle changes which could cause issues.

**Comment by bkrantz** [comment]
So we can't completely remove __ slots __ from Event without also removing the functionality of __ slots __ from LogEvent (or messing up conversions).  Everything I've ready says and all my testing shows that by just having __ dict __ in __ slots __ is functionally equivalent to not having __ slots __ at all.

With these latest changes I also added a PendingDeprecationWarning to the __ dict __ attribute so we can easily identify potential issues and address them prior to switching all events to using __ slots __.

**Pull request merged**
